name: Auto Comment
on: [ issues, pull_request ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v4.5
      - uses: bubkoo/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: >
            Hi @{{ author }}.

            Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.

            Please make sure you have given us as much context as possible.
          pullRequestOpened: >
            Hi @{{ author }}.

            Thank you for raising your pull request.

            Please make sure you have followed our contributing guidelines. We will review it as soon as possible.

            ## See your changes with

            - [development data](https://s3.cloud.cyfronet.pl/eosc-portal-common/pr-${{ steps.branch-name.outputs.current_branch }}/index.development.html)

            <script src="https://s3.cloud.cyfronet.pl/eosc-portal-common/pr-${{ steps.branch-name.outputs.current_branch }}/index.development.js"></script>

            <link rel="stylesheet" href="https://s3.cloud.cyfronet.pl/eosc-portal-common/pr-${{ steps.branch-name.outputs.current_branch }}/index.development.min.css" />

            - [production data](https://s3.cloud.cyfronet.pl/eosc-portal-common/pr-${{ steps.branch-name.outputs.current_branch }}/index.production.html)

            <script src="https://s3.cloud.cyfronet.pl/eosc-portal-common/pr-${{ steps.branch-name.outputs.current_branch }}/index.production.js"></script>

            <link rel="stylesheet" href="https://s3.cloud.cyfronet.pl/eosc-portal-common/pr-${{ steps.branch-name.outputs.current_branch }}/index.production.min.css" />
