name: Release latest changelog
on:
  push:
    branches:
      - 'develop'
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  release-latest-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest"
