name: Remove Pull Request dist from s3
on:
  pull_request:
    branches:
      - '**'
      - '!master'
      - '!development'
    types:
      - closed

jobs:
  remove-old-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "pr-${GITHUB_HEAD_REF}"
      - name: Sleep for 20min
        uses: juliangruber/sleep-action@v1
        with:
          time: 600s
      - name: Remove from S3
        uses: vitorsgomes/s3-rm-action@master
        with:
          args: --recursive
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          PATH_TO_DELETE: "pr-${GITHUB_HEAD_REF}"
