name: Run unit tests
on:
  pull_request:
    branches:
      - '**'
      - '!develop'
      - '!master'
    types:
      - opened
      - reopened
  push:
    branches:
      - '**'
      - '!develop'
      - '!master'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - uses: actions/setup-node@v2
        if: PULL_NUMBER
        with:
          node-version: '14'
      - name: Cache node modules
        if: PULL_NUMBER
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependecies
        if: PULL_NUMBER
        run: npm install
      - name: Run unit tests
        if: PULL_NUMBER
        run: npm test
