name: Update documentation
on:
  push:
    branches:
      - master
jobs:
  update-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependecies
        run: npm install && npm install -g gulp-cli
      - name: Build documentation & related
        run: gulp build_doc --mode production --env env/env.production.js --dist_path https://s3.cloud.cyfronet.pl/eosc-portal-common/
      - name: Push to documentation branch
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: documentation
          folder: dist
